name: quickdate_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Core
  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  pull_to_refresh: ^2.0.0
  fluttertoast: ^8.2.2

  # Network & Utils
  http: ^1.1.0
  intl: ^0.20.2
  crypto: ^3.0.6
  uuid: ^4.0.0
  connectivity_plus: ^6.0.3
  share_plus: ^12.0.1
  url_launcher: ^6.1.12

  # Storage & Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  shared_preferences: ^2.1.1
  sqflite: ^2.2.5
  path: ^1.8.3

  # Auth & Payments
  google_sign_in: ^6.0.0
  flutter_facebook_auth: ^6.0.4
  razorpay_flutter: ^1.3.1
  country_picker: ^2.0.15

  # Media & Permissions
  camera: ^0.10.5
  video_player: ^2.8.0
  image_picker: ^1.0.7
  permission_handler: ^11.0.0

  # Miscellaneous
  universal_html: ^2.2.1
  emoji_picker_flutter: ^1.1.0
  clipboard: ^0.1.3
  webview_flutter: ^4.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # ✅ Added for localization & code generation
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2

  # ✅ Optional but useful for Hive & JSON models
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/Google_logo.png
    - assets/images/wowonder.png
    - assets/images/icon.png
    - assets/images/icon_splash.png
    - assets/images/TitileImages.png
    - assets/authorize/accept.html
